# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TriggerPipeline@1
  inputs:
    serviceConnection: 'trigger'
    project: 'b32c8965-6f2a-4655-8858-9ea83ec0126c'
    Pipeline: 'Build'
    buildDefinition: 'leonidmal8registrartion.azureDovops'
    Branch: 'master'